---
# - hosts: localhost
#   gather_facts: True
#   check_mode: no
#   vars:
#     host: 116.203.107.188
#   tasks:
#   - name: Add public ip addresses to an dynamic inventory
#     add_host:
#       name: "{{ host }}"
#       groups: all
#
#   - local_action: wait_for port=22 host="{{ host }}" search_regex=OpenSSH delay=10

- hosts: group-webserver
  gather_facts: False
  check_mode: no
  become: True
  pre_tasks:
    - name: Install python 2.7
      raw: >
        test -e /usr/bin/python ||
        (
          (test -e /usr/bin/apt-get && (apt-get -y update && apt-get install -y python)) ||
          (test -e /usr/bin/yum && (yum makecache fast && yum install -y python))
        )
      args:
        creates: /usr/bin/python
      changed_when: False
    - setup:

  tasks:
    -

  # roles:
  # - { role: geerlingguy.nginx }
  # - { role: geerlingguy.docker }
